apiVersion: v1
kind: Service
metadata:
  name: {{ include "guest-book.phpRedis.fullname" . }}
  labels:
{{ include "guest-book.phpRedis.labels" . | indent 4 }}
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
  selector:
{{ include "guest-book.phpRedis.labels" . | indent 6 }}
