# Default values for guest-book.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

phpRedis:
    name: phpredis
    redisMaster: redisbackend-redismaster
    redisSlave: redisbackend-redisslave
    replicaCount: 3
    image:
        repository: gcr.io/google-samples/gb-frontend
        tag: v4
        pullPolicy: IfNotPresent



imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

